/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API version */
        get: operations["api-version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system status */
        get: operations["get-system-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List artifacts */
        get: operations["list-artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an artifact */
        get: operations["get-artifact"];
        put?: never;
        post?: never;
        /** Delete an artifact */
        delete: operations["delete-artifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{id}/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifact changelog */
        get: operations["get-artifact-changelog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{id}/license-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifact license summary */
        get: operations["get-artifact-license-summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{id}/sboms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SBOMs for an artifact */
        get: operations["list-artifact-sboms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys */
        get: operations["list-api-keys"];
        put?: never;
        /** Create API key */
        post: operations["create-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete API key */
        delete: operations["delete-api-key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search components */
        get: operations["search-components"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components/distinct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search distinct components */
        get: operations["search-distinct-components"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components/purl-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List component PURL types */
        get: operations["list-component-purl-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get component versions */
        get: operations["get-component-versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a component */
        get: operations["get-component"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff two SBOMs
         * @description Computes the component diff between two SBOMs.
         */
        get: operations["diff-sboms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List licenses */
        get: operations["list-licenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licenses/{id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List components by license */
        get: operations["list-components-by-license"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SBOMs */
        get: operations["list-sboms"];
        put?: never;
        /**
         * Ingest an SBOM
         * @description Accepts a CycloneDX JSON SBOM, validates it, and persists it.
         */
        post: operations["ingest-sbom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sbom/by-digest/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SBOMs by image digest */
        get: operations["list-sboms-by-digest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sbom/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an SBOM */
        get: operations["get-sbom"];
        put?: never;
        post?: never;
        /** Delete an SBOM */
        delete: operations["delete-sbom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sbom/{id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List components in an SBOM */
        get: operations["list-sbom-components"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sbom/{id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get SBOM dependency graph */
        get: operations["get-sbom-dependencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary statistics */
        get: operations["get-dashboard-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["list-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user role */
        patch: operations["update-user-role"];
        trace?: never;
    };
    "/api/v1/webhooks/zot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Zot registry push notifications */
        post: operations["zot-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Verifies the database is reachable.
         */
        get: operations["readiness-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIKeyMetaResponse: {
            /** Format: date-time */
            created_at: string;
            /** @description Key UUID */
            id: string;
            /** Format: date-time */
            last_used_at?: string;
            name: string;
            /** @description First 8 characters of the key */
            prefix: string;
        };
        ArtifactDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ArtifactDetail.json
             */
            readonly $schema?: string;
            cpe?: string;
            /** Format: date-time */
            createdAt: string;
            group?: string;
            id: string;
            name: string;
            purl?: string;
            /** Format: int64 */
            sbomCount: number;
            type: string;
        };
        ArtifactSummary: {
            group?: string;
            id: string;
            name: string;
            /** Format: int64 */
            sbomCount: number;
            type: string;
        };
        CategoryCountEntry: {
            category: string;
            /** Format: int64 */
            component_count: number;
        };
        ChangeSummary: {
            /** Format: int64 */
            added: number;
            /** Format: int64 */
            modified: number;
            /** Format: int64 */
            removed: number;
        };
        Changelog: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Changelog.json
             */
            readonly $schema?: string;
            artifactId: string;
            availableArchitectures: string[] | null;
            entries: components["schemas"]["ChangelogEntry"][] | null;
        };
        ChangelogEntry: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChangelogEntry.json
             */
            readonly $schema?: string;
            changes: components["schemas"]["ComponentDiff"][] | null;
            from: components["schemas"]["SBOMRef"];
            summary: components["schemas"]["ChangeSummary"];
            to: components["schemas"]["SBOMRef"];
        };
        ComponentDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ComponentDetail.json
             */
            readonly $schema?: string;
            bomRef?: string;
            copyright?: string;
            cpe?: string;
            description?: string;
            externalReferences: components["schemas"]["ExternalRefEntry"][] | null;
            group?: string;
            hashes: components["schemas"]["HashEntry"][] | null;
            id: string;
            licenses: components["schemas"]["LicenseSummary"][] | null;
            name: string;
            publisher?: string;
            purl?: string;
            sbomId: string;
            scope?: string;
            type: string;
            version?: string;
        };
        ComponentDiff: {
            group?: string;
            name: string;
            previousVersion?: string;
            purl?: string;
            type: string;
            version?: string;
        };
        ComponentSummary: {
            bomRef?: string;
            group?: string;
            id: string;
            name: string;
            purl?: string;
            sbomId: string;
            type: string;
            version?: string;
        };
        ComponentVersionEntry: {
            architecture?: string;
            artifactId?: string;
            artifactName?: string;
            group?: string;
            id: string;
            name: string;
            purl?: string;
            sbomCreatedAt: string;
            sbomDigest?: string;
            sbomId: string;
            subjectVersion?: string;
            type: string;
            version?: string;
        };
        CreateAPIKeyInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateAPIKeyInputBody.json
             */
            readonly $schema?: string;
            /** @description Human-readable label for this key */
            name: string;
        };
        CreateAPIKeyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateAPIKeyOutputBody.json
             */
            readonly $schema?: string;
            /** @description Full API key — shown once, store securely */
            key: string;
        };
        DailyCountEntry: {
            /** Format: int64 */
            count: number;
            day: string;
        };
        DashboardStatsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DashboardStatsOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            artifact_count: number;
            ingestion_timeline: components["schemas"]["DailyCountEntry"][] | null;
            license_categories: components["schemas"]["CategoryCountEntry"][] | null;
            /** Format: int64 */
            license_count: number;
            /** Format: int64 */
            package_count: number;
            package_growth_timeline: components["schemas"]["DailyCountEntry"][] | null;
            /** Format: int64 */
            sbom_count: number;
            top_packages: components["schemas"]["PackageSummaryEntry"][] | null;
            /** Format: int64 */
            version_count: number;
            version_growth_timeline: components["schemas"]["DailyCountEntry"][] | null;
        };
        DependencyEdge: {
            from: string;
            to: string;
        };
        DependencyGraph: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DependencyGraph.json
             */
            readonly $schema?: string;
            edges: components["schemas"]["DependencyEdge"][] | null;
            nodes: components["schemas"]["ComponentSummary"][] | null;
        };
        DistinctComponentSummary: {
            group?: string;
            name: string;
            purlTypes?: string[] | null;
            /** Format: int64 */
            sbomCount: number;
            type: string;
            /** Format: int64 */
            versionCount: number;
        };
        EnrichmentStatus: {
            enabled: boolean;
            /** Format: int64 */
            queue_size: number;
            /** Format: int64 */
            workers: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ExternalRefEntry: {
            comment?: string;
            type: string;
            url: string;
        };
        GetArtifactLicenseSummaryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetArtifactLicenseSummaryOutputBody.json
             */
            readonly $schema?: string;
            licenses: components["schemas"]["LicenseCount"][] | null;
        };
        GetComponentVersionsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetComponentVersionsOutputBody.json
             */
            readonly $schema?: string;
            versions: components["schemas"]["ComponentVersionEntry"][] | null;
        };
        HashEntry: {
            algorithm: string;
            value: string;
        };
        HealthCheckOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthCheckOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Health status
             * @example ok
             */
            status: string;
        };
        IngestSBOMOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/IngestSBOMOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of components in the SBOM
             */
            componentCount: number;
            /** @description UUID of the created SBOM */
            id: string;
            /** @description SBOM serial number */
            serialNumber?: string;
            /** @description CycloneDX spec version */
            specVersion: string;
            /**
             * @description Ingestion status
             * @example accepted
             */
            status: string;
        };
        LicenseCount: {
            category: string;
            /** Format: int64 */
            componentCount: number;
            id: string;
            name: string;
            spdxId?: string;
            url?: string;
        };
        LicenseSummary: {
            id: string;
            name: string;
            spdxId?: string;
            url?: string;
        };
        ListAPIKeysOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListAPIKeysOutputBody.json
             */
            readonly $schema?: string;
            keys: components["schemas"]["APIKeyMetaResponse"][] | null;
        };
        ListArtifactSBOMsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListArtifactSBOMsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SBOMSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        ListArtifactsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListArtifactsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["ArtifactSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        ListComponentPurlTypesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListComponentPurlTypesOutputBody.json
             */
            readonly $schema?: string;
            types: string[] | null;
        };
        ListComponentsByLicenseOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListComponentsByLicenseOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["ComponentSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        ListLicensesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListLicensesOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["LicenseCount"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        ListSBOMComponentsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSBOMComponentsOutputBody.json
             */
            readonly $schema?: string;
            components: components["schemas"]["ComponentSummary"][] | null;
        };
        ListSBOMsByDigestOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSBOMsByDigestOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SBOMSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        ListSBOMsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSBOMsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SBOMSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        ListUsersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListUsersOutputBody.json
             */
            readonly $schema?: string;
            users: components["schemas"]["UserResponse"][] | null;
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            /** @description GitHub login */
            github_username: string;
            /** @description User UUID */
            id: string;
            /** @description User role: admin, member, or viewer */
            role: string;
        };
        NATSStatus: {
            enabled: boolean;
            url: string;
        };
        PackageSummaryEntry: {
            group?: string;
            name: string;
            /** Format: int64 */
            sbom_count: number;
            type: string;
            /** Format: int64 */
            version_count: number;
        };
        PaginationMeta: {
            /**
             * Format: int32
             * @description The limit that was applied
             */
            limit: number;
            /**
             * Format: int32
             * @description The offset that was applied
             */
            offset: number;
            /**
             * Format: int64
             * @description Total number of matching results
             */
            total: number;
        };
        ReadinessCheckOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReadinessCheckOutputBody.json
             */
            readonly $schema?: string;
            /** @description Reason for unavailability */
            reason?: string;
            /**
             * @description Readiness status
             * @example ready
             */
            status: string;
        };
        SBOMDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SBOMDetail.json
             */
            readonly $schema?: string;
            architecture?: string;
            artifactId?: string;
            /** Format: date-time */
            buildDate?: string;
            /** Format: int64 */
            componentCount?: number;
            /** Format: date-time */
            createdAt: string;
            digest?: string;
            enrichments?: Record<string, unknown>;
            id: string;
            imageVersion?: string;
            rawBom?: unknown;
            serialNumber?: string;
            specVersion: string;
            subjectVersion?: string;
            /** Format: int32 */
            version: number;
        };
        SBOMRef: {
            architecture?: string;
            /** Format: date-time */
            buildDate?: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            subjectVersion?: string;
        };
        SBOMSummary: {
            architecture?: string;
            artifactId?: string;
            /** Format: date-time */
            buildDate?: string;
            /** Format: int64 */
            componentCount?: number;
            /** Format: date-time */
            createdAt: string;
            digest?: string;
            id: string;
            imageVersion?: string;
            serialNumber?: string;
            specVersion: string;
            subjectVersion?: string;
            /** Format: int32 */
            version: number;
        };
        ScannerStatus: {
            enabled: boolean;
        };
        SearchComponentsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchComponentsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["ComponentSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        SearchDistinctComponentsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SearchDistinctComponentsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["DistinctComponentSummary"][] | null;
            pagination: components["schemas"]["PaginationMeta"];
        };
        SystemStatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SystemStatusOutputBody.json
             */
            readonly $schema?: string;
            enrichment: components["schemas"]["EnrichmentStatus"];
            nats: components["schemas"]["NATSStatus"];
            scanner: components["schemas"]["ScannerStatus"];
        };
        UpdateUserRoleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateUserRoleInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description New role
             * @enum {string}
             */
            role: "admin" | "member" | "viewer";
        };
        UserResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UserResponse.json
             */
            readonly $schema?: string;
            github_username: string;
            id: string;
            role: string;
        };
        VersionOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/VersionOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description API version
             * @example v1
             */
            version: string;
        };
        ZotEvent: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ZotEvent.json
             */
            readonly $schema?: string;
            digest: string;
            manifest: string;
            mediaType: string;
            name: string;
            reference: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "api-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["VersionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-system-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SystemStatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-artifacts": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter by artifact type */
                type?: string;
                /** @description Filter by artifact name */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListArtifactsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-artifact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-artifact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: Record<string, unknown>;
                content?: never;
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-artifact-changelog": {
        parameters: {
            query?: {
                /** @description Filter by subject version */
                subject_version?: string;
                /** @description Architecture to show timeline for (e.g. amd64) */
                arch?: string;
            };
            header?: never;
            path: {
                /** @description Artifact UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["Changelog"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-artifact-license-summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["GetArtifactLicenseSummaryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-artifact-sboms": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter by subject version */
                subject_version?: string;
                /** @description Filter by image version */
                image_version?: string;
            };
            header?: never;
            path: {
                /** @description Artifact UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListArtifactSBOMsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListAPIKeysOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["CreateAPIKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Key UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: Record<string, unknown>;
                content?: never;
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-components": {
        parameters: {
            query: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Component name to search for */
                name: string;
                /** @description Filter by component group */
                group?: string;
                /** @description Filter by component version */
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SearchComponentsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-distinct-components": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter by component name */
                name?: string;
                /** @description Filter by component group */
                group?: string;
                /** @description Filter by component type */
                type?: string;
                /** @description Filter by purl type */
                purl_type?: string;
                /** @description Sort field */
                sort?: string;
                /** @description Sort direction (asc or desc) */
                sort_dir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SearchDistinctComponentsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-component-purl-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListComponentPurlTypesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-component-versions": {
        parameters: {
            query: {
                /** @description Component name */
                name: string;
                /** @description Filter by component group */
                group?: string;
                /** @description Filter by component version */
                version?: string;
                /** @description Filter by component type */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["GetComponentVersionsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Component UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ComponentDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "diff-sboms": {
        parameters: {
            query: {
                /** @description UUID of the source SBOM */
                from: string;
                /** @description UUID of the target SBOM */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ChangelogEntry"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-licenses": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter by SPDX identifier */
                spdx_id?: string;
                /** @description Filter by license name */
                name?: string;
                /** @description Filter by license category */
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListLicensesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-components-by-license": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description License UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListComponentsByLicenseOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sboms": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter by serial number */
                serial_number?: string;
                /** @description Filter by image digest */
                digest?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListSBOMsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ingest-sbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["IngestSBOMOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sboms-by-digest": {
        parameters: {
            query?: {
                /** @description Maximum number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Image digest (e.g. sha256:abc123) */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListSBOMsByDigestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-sbom": {
        parameters: {
            query?: {
                /** @description Set to 'raw' to include the raw BOM JSON */
                include?: string;
            };
            header?: never;
            path: {
                /** @description SBOM UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SBOMDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-sbom": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SBOM UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: Record<string, unknown>;
                content?: never;
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sbom-components": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SBOM UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListSBOMComponentsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-sbom-dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SBOM UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["DependencyGraph"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-dashboard-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["DashboardStatsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ListUsersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-user-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRoleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "zot-webhook": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZotEvent"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: Record<string, unknown>;
                content?: never;
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HealthCheckOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "readiness-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ReadinessCheckOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: Record<string, unknown>;
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
