apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ocidex-ocidex-pull-request
  namespace: ocidex-ci
spec:
  params:
    - name: project-name
      type: string
    - name: repo-full-name
      type: string
    - name: revision
      type: string
    - name: url
      type: string
  tasks:
    - name: set-status-pending
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: ocidex-set-status-pending
    - name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      taskRef:
        kind: Task
        name: ocidex-git-clone
      workspaces:
        - name: workspace
          workspace: workspace
    - name: go-fmt
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - set-status-pending
      taskRef:
        kind: Task
        name: ocidex-go-fmt
      workspaces:
        - name: workspace
          workspace: workspace
    - name: go-lint
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - go-fmt
        - set-status-pending
      taskRef:
        kind: Task
        name: ocidex-go-lint
      workspaces:
        - name: go-cache
          workspace: go-cache
        - name: workspace
          workspace: workspace
    - name: go-test
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - go-lint
        - set-status-pending
      taskRef:
        kind: Task
        name: ocidex-go-test
      workspaces:
        - name: go-cache
          workspace: go-cache
        - name: workspace
          workspace: workspace
    - name: go-build
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - go-test
        - set-status-pending
      taskRef:
        kind: Task
        name: ocidex-go-build
      workspaces:
        - name: go-cache
          workspace: go-cache
        - name: workspace
          workspace: workspace
    - name: openapi-check
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - go-test
        - set-status-pending
      taskRef:
        kind: Task
        name: ocidex-openapi-check
      workspaces:
        - name: go-cache
          workspace: go-cache
        - name: node-cache
          workspace: node-cache
        - name: workspace
          workspace: workspace
    - name: frontend-lint
      params:
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
      runAfter:
        - openapi-check
        - set-status-pending
      taskRef:
        kind: Task
        name: ocidex-frontend-lint
      workspaces:
        - name: node-cache
          workspace: node-cache
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
    - name: go-cache
    - name: node-cache
