apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: ocidex-set-status-pending
  namespace: ocidex-ci
spec:
  params:
    - name: repo-full-name
      type: string
    - name: revision
      type: string
  stepTemplate:
    computeResources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  steps:
    - args:
        - 'curl -fsS -X POST   -H "Authorization: token $GITHUB_TOKEN"   -H "Accept: application/vnd.github+json"   -H "Content-Type: application/json"   -d "{\"state\":\"pending\",\"context\":\"ocidex/fmt\",\"description\":\"Running\"}"   "https://api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)"'
      command:
        - sh
        - -c
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      image: cgr.dev/chainguard/curl:latest-dev
      name: pending-ocidex-fmt
    - args:
        - 'curl -fsS -X POST   -H "Authorization: token $GITHUB_TOKEN"   -H "Accept: application/vnd.github+json"   -H "Content-Type: application/json"   -d "{\"state\":\"pending\",\"context\":\"ocidex/lint\",\"description\":\"Running\"}"   "https://api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)"'
      command:
        - sh
        - -c
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      image: cgr.dev/chainguard/curl:latest-dev
      name: pending-ocidex-lint
    - args:
        - 'curl -fsS -X POST   -H "Authorization: token $GITHUB_TOKEN"   -H "Accept: application/vnd.github+json"   -H "Content-Type: application/json"   -d "{\"state\":\"pending\",\"context\":\"ocidex/test\",\"description\":\"Running\"}"   "https://api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)"'
      command:
        - sh
        - -c
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      image: cgr.dev/chainguard/curl:latest-dev
      name: pending-ocidex-test
    - args:
        - 'curl -fsS -X POST   -H "Authorization: token $GITHUB_TOKEN"   -H "Accept: application/vnd.github+json"   -H "Content-Type: application/json"   -d "{\"state\":\"pending\",\"context\":\"ocidex/build\",\"description\":\"Running\"}"   "https://api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)"'
      command:
        - sh
        - -c
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      image: cgr.dev/chainguard/curl:latest-dev
      name: pending-ocidex-build
    - args:
        - 'curl -fsS -X POST   -H "Authorization: token $GITHUB_TOKEN"   -H "Accept: application/vnd.github+json"   -H "Content-Type: application/json"   -d "{\"state\":\"pending\",\"context\":\"ocidex/openapi\",\"description\":\"Running\"}"   "https://api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)"'
      command:
        - sh
        - -c
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      image: cgr.dev/chainguard/curl:latest-dev
      name: pending-ocidex-openapi
    - args:
        - 'curl -fsS -X POST   -H "Authorization: token $GITHUB_TOKEN"   -H "Accept: application/vnd.github+json"   -H "Content-Type: application/json"   -d "{\"state\":\"pending\",\"context\":\"ocidex/frontend-lint\",\"description\":\"Running\"}"   "https://api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)"'
      command:
        - sh
        - -c
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      image: cgr.dev/chainguard/curl:latest-dev
      name: pending-ocidex-frontend-lint
