// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifact.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteArtifact = `-- name: DeleteArtifact :execrows
DELETE FROM artifact WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSBOMsByArtifact = `-- name: DeleteSBOMsByArtifact :execrows
DELETE FROM sbom WHERE artifact_id = $1
`

func (q *Queries) DeleteSBOMsByArtifact(ctx context.Context, artifactID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSBOMsByArtifact, artifactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, type, name, group_name, purl, cpe, created_at
FROM artifact
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.GroupName,
		&i.Purl,
		&i.Cpe,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactOwnerID = `-- name: GetArtifactOwnerID :one
SELECT r.owner_id
FROM artifact_registry ar
JOIN registry r ON r.id = ar.registry_id
WHERE ar.artifact_id = $1 AND r.owner_id IS NOT NULL
LIMIT 1
`

func (q *Queries) GetArtifactOwnerID(ctx context.Context, artifactID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getArtifactOwnerID, artifactID)
	var owner_id pgtype.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT a.id, a.type, a.name, a.group_name, a.purl, a.cpe, a.created_at,
       COUNT(s.id) AS sbom_count,
       COUNT(s.id) FILTER (WHERE s.enrichment_sufficient) AS sufficient_sbom_count,
       COUNT(*) OVER() AS total_count
FROM artifact a
LEFT JOIN sbom s ON s.artifact_id = a.id
WHERE ($1::text IS NULL OR a.type = $1)
  AND ($2::text IS NULL OR a.name = $2)
  AND ($3::boolean IS NULL
       OR NOT $3::boolean
       OR EXISTS (SELECT 1 FROM sbom s2 WHERE s2.artifact_id = a.id AND s2.enrichment_sufficient))
  AND artifact_visible(a.id, $4::uuid, $5::boolean)
GROUP BY a.id
ORDER BY a.name, a.type
LIMIT $7 OFFSET $6
`

type ListArtifactsParams struct {
	Type              pgtype.Text `json:"type"`
	Name              pgtype.Text `json:"name"`
	RequireSufficient pgtype.Bool `json:"require_sufficient"`
	UserID            pgtype.UUID `json:"user_id"`
	IsAdmin           pgtype.Bool `json:"is_admin"`
	RowOffset         int32       `json:"row_offset"`
	RowLimit          int32       `json:"row_limit"`
}

type ListArtifactsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Type                string             `json:"type"`
	Name                string             `json:"name"`
	GroupName           pgtype.Text        `json:"group_name"`
	Purl                pgtype.Text        `json:"purl"`
	Cpe                 pgtype.Text        `json:"cpe"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	SbomCount           int64              `json:"sbom_count"`
	SufficientSbomCount int64              `json:"sufficient_sbom_count"`
	TotalCount          int64              `json:"total_count"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArtifacts,
		arg.Type,
		arg.Name,
		arg.RequireSufficient,
		arg.UserID,
		arg.IsAdmin,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsRow{}
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Purl,
			&i.Cpe,
			&i.CreatedAt,
			&i.SbomCount,
			&i.SufficientSbomCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMsByArtifact = `-- name: ListSBOMsByArtifact :many
SELECT s.id, s.serial_number, s.spec_version, s.version, s.subject_version, s.digest, s.created_at,
       (SELECT COUNT(*) FROM component c WHERE c.sbom_id = s.id) AS component_count,
       (COALESCE(e.data->>'created', u.data->>'created'))::timestamptz AS build_date,
       COALESCE(e.data->>'imageVersion', u.data->>'imageVersion') AS image_version,
       COALESCE(e.data->>'architecture', u.data->>'architecture') AS architecture,
       COALESCE(e.data->>'revision', u.data->>'revision') AS revision,
       COALESCE(e.data->>'sourceUrl', u.data->>'sourceUrl') AS source_url,
       s.enrichment_sufficient,
       COUNT(*) OVER() AS total_count
FROM sbom s
LEFT JOIN enrichment e ON e.sbom_id = s.id AND e.enricher_name = 'oci-metadata' AND e.status = 'success'
LEFT JOIN enrichment u ON u.sbom_id = s.id AND u.enricher_name = 'user' AND u.status = 'success'
WHERE s.artifact_id = $1
  AND ($2::text IS NULL OR s.subject_version = $2)
  AND ($3::text IS NULL
       OR COALESCE(e.data->>'imageVersion', u.data->>'imageVersion') = $3)
  AND sbom_visible(s.registry_id, $4::uuid, $5::boolean)
ORDER BY s.created_at DESC
LIMIT $7 OFFSET $6
`

type ListSBOMsByArtifactParams struct {
	ArtifactID     pgtype.UUID `json:"artifact_id"`
	SubjectVersion pgtype.Text `json:"subject_version"`
	ImageVersion   pgtype.Text `json:"image_version"`
	UserID         pgtype.UUID `json:"user_id"`
	IsAdmin        pgtype.Bool `json:"is_admin"`
	RowOffset      int32       `json:"row_offset"`
	RowLimit       int32       `json:"row_limit"`
}

type ListSBOMsByArtifactRow struct {
	ID                   pgtype.UUID        `json:"id"`
	SerialNumber         pgtype.Text        `json:"serial_number"`
	SpecVersion          string             `json:"spec_version"`
	Version              int32              `json:"version"`
	SubjectVersion       pgtype.Text        `json:"subject_version"`
	Digest               pgtype.Text        `json:"digest"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ComponentCount       int64              `json:"component_count"`
	BuildDate            pgtype.Timestamptz `json:"build_date"`
	ImageVersion         interface{}        `json:"image_version"`
	Architecture         interface{}        `json:"architecture"`
	Revision             interface{}        `json:"revision"`
	SourceUrl            interface{}        `json:"source_url"`
	EnrichmentSufficient bool               `json:"enrichment_sufficient"`
	TotalCount           int64              `json:"total_count"`
}

func (q *Queries) ListSBOMsByArtifact(ctx context.Context, arg ListSBOMsByArtifactParams) ([]ListSBOMsByArtifactRow, error) {
	rows, err := q.db.Query(ctx, listSBOMsByArtifact,
		arg.ArtifactID,
		arg.SubjectVersion,
		arg.ImageVersion,
		arg.UserID,
		arg.IsAdmin,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMsByArtifactRow{}
	for rows.Next() {
		var i ListSBOMsByArtifactRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.SpecVersion,
			&i.Version,
			&i.SubjectVersion,
			&i.Digest,
			&i.CreatedAt,
			&i.ComponentCount,
			&i.BuildDate,
			&i.ImageVersion,
			&i.Architecture,
			&i.Revision,
			&i.SourceUrl,
			&i.EnrichmentSufficient,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifact (type, name, group_name, purl, cpe)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (type, name, COALESCE(group_name, ''))
DO UPDATE SET
    purl = COALESCE(EXCLUDED.purl, artifact.purl),
    cpe  = COALESCE(EXCLUDED.cpe, artifact.cpe)
RETURNING id
`

type UpsertArtifactParams struct {
	Type      string      `json:"type"`
	Name      string      `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
	Purl      pgtype.Text `json:"purl"`
	Cpe       pgtype.Text `json:"cpe"`
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.Type,
		arg.Name,
		arg.GroupName,
		arg.Purl,
		arg.Cpe,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertArtifactRegistry = `-- name: UpsertArtifactRegistry :exec
INSERT INTO artifact_registry (artifact_id, registry_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertArtifactRegistryParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	RegistryID pgtype.UUID `json:"registry_id"`
}

func (q *Queries) UpsertArtifactRegistry(ctx context.Context, arg UpsertArtifactRegistryParams) error {
	_, err := q.db.Exec(ctx, upsertArtifactRegistry, arg.ArtifactID, arg.RegistryID)
	return err
}
