// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_key (user_id, name, key_hash, prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, key_hash, prefix, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Name    string      `json:"name"`
	KeyHash string      `json:"key_hash"`
	Prefix  string      `json:"prefix"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO session (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_key WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.user_id, k.name, k.key_hash, k.prefix, k.created_at, k.last_used_at, u.github_id, u.github_username, u.role
FROM api_key k
JOIN ocidex_user u ON u.id = k.user_id
WHERE k.key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	KeyHash        string             `json:"key_hash"`
	Prefix         string             `json:"prefix"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	GithubID       int64              `json:"github_id"`
	GithubUsername string             `json:"github_username"`
	Role           string             `json:"role"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.GithubID,
		&i.GithubUsername,
		&i.Role,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.expires_at, s.created_at, u.github_id, u.github_username, u.role
FROM session s
JOIN ocidex_user u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	GithubID       int64              `json:"github_id"`
	GithubUsername string             `json:"github_username"`
	Role           string             `json:"role"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.GithubID,
		&i.GithubUsername,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, github_username, role, created_at, updated_at FROM ocidex_user WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, name, prefix, created_at, last_used_at
FROM api_key
WHERE user_id = $1
ORDER BY created_at ASC
`

type ListAPIKeysByUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_id, github_username, role, created_at, updated_at FROM ocidex_user ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]OcidexUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcidexUser{}
	for rows.Next() {
		var i OcidexUser
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.GithubUsername,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_key SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE ocidex_user
SET role       = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, github_id, github_username, role, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO ocidex_user (github_id, github_username)
VALUES ($1, $2)
ON CONFLICT (github_id) DO UPDATE
    SET github_username = EXCLUDED.github_username,
        updated_at      = now()
RETURNING id, github_id, github_username, role, created_at, updated_at
`

type UpsertUserParams struct {
	GithubID       int64  `json:"github_id"`
	GithubUsername string `json:"github_username"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (OcidexUser, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.GithubID, arg.GithubUsername)
	var i OcidexUser
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
