// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Artifact struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Name      string             `json:"name"`
	GroupName pgtype.Text        `json:"group_name"`
	Purl      pgtype.Text        `json:"purl"`
	Cpe       pgtype.Text        `json:"cpe"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Component struct {
	ID           pgtype.UUID `json:"id"`
	SbomID       pgtype.UUID `json:"sbom_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	BomRef       pgtype.Text `json:"bom_ref"`
	Type         string      `json:"type"`
	Name         string      `json:"name"`
	GroupName    pgtype.Text `json:"group_name"`
	Version      pgtype.Text `json:"version"`
	VersionMajor pgtype.Int4 `json:"version_major"`
	VersionMinor pgtype.Int4 `json:"version_minor"`
	VersionPatch pgtype.Int4 `json:"version_patch"`
	Purl         pgtype.Text `json:"purl"`
	Cpe          pgtype.Text `json:"cpe"`
	Description  pgtype.Text `json:"description"`
	Scope        pgtype.Text `json:"scope"`
	Publisher    pgtype.Text `json:"publisher"`
	Copyright    pgtype.Text `json:"copyright"`
}

type ComponentHash struct {
	ID          pgtype.UUID `json:"id"`
	ComponentID pgtype.UUID `json:"component_id"`
	Algorithm   string      `json:"algorithm"`
	Value       string      `json:"value"`
}

type ComponentLicense struct {
	ComponentID pgtype.UUID `json:"component_id"`
	LicenseID   pgtype.UUID `json:"license_id"`
}

type Dependency struct {
	ID        pgtype.UUID `json:"id"`
	SbomID    pgtype.UUID `json:"sbom_id"`
	Ref       string      `json:"ref"`
	DependsOn string      `json:"depends_on"`
}

type Enrichment struct {
	ID           pgtype.UUID        `json:"id"`
	SbomID       pgtype.UUID        `json:"sbom_id"`
	EnricherName string             `json:"enricher_name"`
	Status       string             `json:"status"`
	Data         []byte             `json:"data"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ExternalReference struct {
	ID          pgtype.UUID `json:"id"`
	ComponentID pgtype.UUID `json:"component_id"`
	Type        string      `json:"type"`
	Url         string      `json:"url"`
	Comment     pgtype.Text `json:"comment"`
}

type License struct {
	ID     pgtype.UUID `json:"id"`
	SpdxID pgtype.Text `json:"spdx_id"`
	Name   string      `json:"name"`
	Url    pgtype.Text `json:"url"`
}

type OcidexUser struct {
	ID             pgtype.UUID        `json:"id"`
	GithubID       int64              `json:"github_id"`
	GithubUsername string             `json:"github_username"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Registry struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Url                 string             `json:"url"`
	Insecure            bool               `json:"insecure"`
	WebhookSecret       pgtype.Text        `json:"webhook_secret"`
	Enabled             bool               `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RepositoryPatterns  []string           `json:"repository_patterns"`
	TagPatterns         []string           `json:"tag_patterns"`
	ScanMode            string             `json:"scan_mode"`
	PollIntervalMinutes int32              `json:"poll_interval_minutes"`
	LastPolledAt        pgtype.Timestamptz `json:"last_polled_at"`
	Repositories        []string           `json:"repositories"`
	AuthUsername        pgtype.Text        `json:"auth_username"`
	AuthToken           pgtype.Text        `json:"auth_token"`
}

type Sbom struct {
	ID                   pgtype.UUID        `json:"id"`
	SerialNumber         pgtype.Text        `json:"serial_number"`
	SpecVersion          string             `json:"spec_version"`
	Version              int32              `json:"version"`
	RawBom               []byte             `json:"raw_bom"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ArtifactID           pgtype.UUID        `json:"artifact_id"`
	SubjectVersion       pgtype.Text        `json:"subject_version"`
	Digest               pgtype.Text        `json:"digest"`
	EnrichmentSufficient bool               `json:"enrichment_sufficient"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
