// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registry (name, type, url, insecure, webhook_secret, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, repositories, auth_username, auth_token, owner_id, visibility, include_untagged)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged
`

type CreateRegistryParams struct {
	Name                string      `json:"name"`
	Type                string      `json:"type"`
	Url                 string      `json:"url"`
	Insecure            bool        `json:"insecure"`
	WebhookSecret       pgtype.Text `json:"webhook_secret"`
	RepositoryPatterns  []string    `json:"repository_patterns"`
	TagPatterns         []string    `json:"tag_patterns"`
	ScanMode            string      `json:"scan_mode"`
	PollIntervalMinutes int32       `json:"poll_interval_minutes"`
	Repositories        []string    `json:"repositories"`
	AuthUsername        pgtype.Text `json:"auth_username"`
	AuthToken           pgtype.Text `json:"auth_token"`
	OwnerID             pgtype.UUID `json:"owner_id"`
	Visibility          string      `json:"visibility"`
	IncludeUntagged     bool        `json:"include_untagged"`
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.Insecure,
		arg.WebhookSecret,
		arg.RepositoryPatterns,
		arg.TagPatterns,
		arg.ScanMode,
		arg.PollIntervalMinutes,
		arg.Repositories,
		arg.AuthUsername,
		arg.AuthToken,
		arg.OwnerID,
		arg.Visibility,
		arg.IncludeUntagged,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.OwnerID,
		&i.Visibility,
		&i.IncludeUntagged,
	)
	return i, err
}

const deleteRegistry = `-- name: DeleteRegistry :execrows
DELETE FROM registry WHERE id = $1
`

func (q *Queries) DeleteRegistry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRegistry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegistry = `-- name: GetRegistry :one
SELECT id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged FROM registry WHERE id = $1
`

func (q *Queries) GetRegistry(ctx context.Context, id pgtype.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistry, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.OwnerID,
		&i.Visibility,
		&i.IncludeUntagged,
	)
	return i, err
}

const listPollableRegistries = `-- name: ListPollableRegistries :many
SELECT id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged FROM registry
WHERE enabled = true AND scan_mode IN ('poll', 'both')
ORDER BY created_at ASC
`

func (q *Queries) ListPollableRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listPollableRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Insecure,
			&i.WebhookSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryPatterns,
			&i.TagPatterns,
			&i.ScanMode,
			&i.PollIntervalMinutes,
			&i.LastPolledAt,
			&i.Repositories,
			&i.AuthUsername,
			&i.AuthToken,
			&i.OwnerID,
			&i.Visibility,
			&i.IncludeUntagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistries = `-- name: ListRegistries :many
SELECT id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged FROM registry
WHERE (
    $1::boolean = true
    OR visibility = 'public'
    OR ($2::uuid IS NOT NULL AND owner_id = $2::uuid)
)
ORDER BY created_at ASC
`

type ListRegistriesParams struct {
	IsAdmin pgtype.Bool `json:"is_admin"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListRegistries(ctx context.Context, arg ListRegistriesParams) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistries, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Insecure,
			&i.WebhookSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryPatterns,
			&i.TagPatterns,
			&i.ScanMode,
			&i.PollIntervalMinutes,
			&i.LastPolledAt,
			&i.Repositories,
			&i.AuthUsername,
			&i.AuthToken,
			&i.OwnerID,
			&i.Visibility,
			&i.IncludeUntagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistriesPaged = `-- name: ListRegistriesPaged :many
SELECT id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged, COUNT(*) OVER() AS total_count FROM registry
WHERE (
    $1::boolean = true
    OR visibility = 'public'
    OR ($2::uuid IS NOT NULL AND owner_id = $2::uuid)
)
ORDER BY created_at ASC
LIMIT $4 OFFSET $3
`

type ListRegistriesPagedParams struct {
	IsAdmin   pgtype.Bool `json:"is_admin"`
	UserID    pgtype.UUID `json:"user_id"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type ListRegistriesPagedRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Url                 string             `json:"url"`
	Insecure            bool               `json:"insecure"`
	WebhookSecret       pgtype.Text        `json:"webhook_secret"`
	Enabled             bool               `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RepositoryPatterns  []string           `json:"repository_patterns"`
	TagPatterns         []string           `json:"tag_patterns"`
	ScanMode            string             `json:"scan_mode"`
	PollIntervalMinutes int32              `json:"poll_interval_minutes"`
	LastPolledAt        pgtype.Timestamptz `json:"last_polled_at"`
	Repositories        []string           `json:"repositories"`
	AuthUsername        pgtype.Text        `json:"auth_username"`
	AuthToken           pgtype.Text        `json:"auth_token"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Visibility          string             `json:"visibility"`
	IncludeUntagged     bool               `json:"include_untagged"`
	TotalCount          int64              `json:"total_count"`
}

func (q *Queries) ListRegistriesPaged(ctx context.Context, arg ListRegistriesPagedParams) ([]ListRegistriesPagedRow, error) {
	rows, err := q.db.Query(ctx, listRegistriesPaged,
		arg.IsAdmin,
		arg.UserID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistriesPagedRow{}
	for rows.Next() {
		var i ListRegistriesPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Insecure,
			&i.WebhookSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryPatterns,
			&i.TagPatterns,
			&i.ScanMode,
			&i.PollIntervalMinutes,
			&i.LastPolledAt,
			&i.Repositories,
			&i.AuthUsername,
			&i.AuthToken,
			&i.OwnerID,
			&i.Visibility,
			&i.IncludeUntagged,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRegistryEnabled = `-- name: SetRegistryEnabled :one
UPDATE registry
SET enabled    = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged
`

type SetRegistryEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) SetRegistryEnabled(ctx context.Context, arg SetRegistryEnabledParams) (Registry, error) {
	row := q.db.QueryRow(ctx, setRegistryEnabled, arg.ID, arg.Enabled)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.OwnerID,
		&i.Visibility,
		&i.IncludeUntagged,
	)
	return i, err
}

const updateRegistry = `-- name: UpdateRegistry :one
UPDATE registry
SET name                 = $2,
    type                 = $3,
    url                  = $4,
    insecure             = $5,
    webhook_secret       = $6,
    enabled              = $7,
    repository_patterns  = $8,
    tag_patterns         = $9,
    scan_mode            = $10,
    poll_interval_minutes = $11,
    repositories         = $12,
    auth_username        = $13,
    auth_token           = $14,
    visibility           = $15,
    include_untagged     = $16,
    updated_at           = now()
WHERE id = $1
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged
`

type UpdateRegistryParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Type                string      `json:"type"`
	Url                 string      `json:"url"`
	Insecure            bool        `json:"insecure"`
	WebhookSecret       pgtype.Text `json:"webhook_secret"`
	Enabled             bool        `json:"enabled"`
	RepositoryPatterns  []string    `json:"repository_patterns"`
	TagPatterns         []string    `json:"tag_patterns"`
	ScanMode            string      `json:"scan_mode"`
	PollIntervalMinutes int32       `json:"poll_interval_minutes"`
	Repositories        []string    `json:"repositories"`
	AuthUsername        pgtype.Text `json:"auth_username"`
	AuthToken           pgtype.Text `json:"auth_token"`
	Visibility          string      `json:"visibility"`
	IncludeUntagged     bool        `json:"include_untagged"`
}

func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistry,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.Insecure,
		arg.WebhookSecret,
		arg.Enabled,
		arg.RepositoryPatterns,
		arg.TagPatterns,
		arg.ScanMode,
		arg.PollIntervalMinutes,
		arg.Repositories,
		arg.AuthUsername,
		arg.AuthToken,
		arg.Visibility,
		arg.IncludeUntagged,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.OwnerID,
		&i.Visibility,
		&i.IncludeUntagged,
	)
	return i, err
}

const updateRegistryLastPolled = `-- name: UpdateRegistryLastPolled :one
UPDATE registry
SET last_polled_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, name, type, url, insecure, webhook_secret, enabled, created_at, updated_at, repository_patterns, tag_patterns, scan_mode, poll_interval_minutes, last_polled_at, repositories, auth_username, auth_token, owner_id, visibility, include_untagged
`

func (q *Queries) UpdateRegistryLastPolled(ctx context.Context, id pgtype.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistryLastPolled, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Insecure,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPatterns,
		&i.TagPatterns,
		&i.ScanMode,
		&i.PollIntervalMinutes,
		&i.LastPolledAt,
		&i.Repositories,
		&i.AuthUsername,
		&i.AuthToken,
		&i.OwnerID,
		&i.Visibility,
		&i.IncludeUntagged,
	)
	return i, err
}
