// Package repository provides the data access layer for OCIDex.
// Most code in this package is generated by sqlc. This file defines
// the repository interface used by the service layer.
package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// SBOMRepository defines the data access methods for SBOM persistence.
type SBOMRepository interface {
	InsertSBOM(ctx context.Context, arg InsertSBOMParams) (InsertSBOMRow, error)
	InsertComponent(ctx context.Context, arg InsertComponentParams) (pgtype.UUID, error)
	InsertComponentHash(ctx context.Context, arg InsertComponentHashParams) error
	UpsertLicenseBySPDX(ctx context.Context, arg UpsertLicenseBySPDXParams) (pgtype.UUID, error)
	UpsertLicenseByName(ctx context.Context, arg UpsertLicenseByNameParams) (pgtype.UUID, error)
	InsertComponentLicense(ctx context.Context, arg InsertComponentLicenseParams) error
	InsertDependency(ctx context.Context, arg InsertDependencyParams) error
	InsertExternalReference(ctx context.Context, arg InsertExternalReferenceParams) error
	DeleteSBOM(ctx context.Context, id pgtype.UUID) (int64, error)
	UpsertArtifactRegistry(ctx context.Context, arg UpsertArtifactRegistryParams) error
}

// SearchRepository defines read-only data access methods for search and retrieval.
type SearchRepository interface {
	GetSBOM(ctx context.Context, id pgtype.UUID) (GetSBOMRow, error)
	GetSBOMRaw(ctx context.Context, id pgtype.UUID) ([]byte, error)
	IsSBOMVisible(ctx context.Context, arg IsSBOMVisibleParams) (bool, error)
	IsArtifactVisible(ctx context.Context, arg IsArtifactVisibleParams) (bool, error)
	ListSBOMs(ctx context.Context, arg ListSBOMsParams) ([]ListSBOMsRow, error)
	SearchComponents(ctx context.Context, arg SearchComponentsParams) ([]SearchComponentsRow, error)
	GetComponent(ctx context.Context, id pgtype.UUID) (GetComponentRow, error)
	ListComponentHashes(ctx context.Context, componentID pgtype.UUID) ([]ListComponentHashesRow, error)
	ListComponentLicenses(ctx context.Context, componentID pgtype.UUID) ([]License, error)
	ListComponentExtRefs(ctx context.Context, componentID pgtype.UUID) ([]ListComponentExtRefsRow, error)
	ListLicenses(ctx context.Context, arg ListLicensesParams) ([]ListLicensesRow, error)
	ListComponentsByLicense(ctx context.Context, arg ListComponentsByLicenseParams) ([]ListComponentsByLicenseRow, error)
	CountSBOMComponents(ctx context.Context, sbomID pgtype.UUID) (int64, error)
	ListSBOMComponents(ctx context.Context, sbomID pgtype.UUID) ([]ListSBOMComponentsRow, error)
	ListSBOMsByDigest(ctx context.Context, arg ListSBOMsByDigestParams) ([]ListSBOMsByDigestRow, error)
	LicenseSummaryByArtifact(ctx context.Context, artifactID pgtype.UUID) ([]LicenseSummaryByArtifactRow, error)
	ListDependenciesBySBOM(ctx context.Context, sbomID pgtype.UUID) ([]ListDependenciesBySBOMRow, error)
	ListComponentPurlTypes(ctx context.Context, arg ListComponentPurlTypesParams) ([]string, error)
	SearchDistinctComponents(ctx context.Context, arg SearchDistinctComponentsParams) ([]SearchDistinctComponentsRow, error)
	GetComponentVersions(ctx context.Context, arg GetComponentVersionsParams) ([]GetComponentVersionsRow, error)
	GetSummaryCounts(ctx context.Context, arg GetSummaryCountsParams) (GetSummaryCountsRow, error)
	GetLicenseCategoryCounts(ctx context.Context, arg GetLicenseCategoryCountsParams) ([]GetLicenseCategoryCountsRow, error)
	GetSBOMIngestionTimeline(ctx context.Context, arg GetSBOMIngestionTimelineParams) ([]GetSBOMIngestionTimelineRow, error)
	GetPackageGrowthTimeline(ctx context.Context, arg GetPackageGrowthTimelineParams) ([]GetPackageGrowthTimelineRow, error)
	GetVersionGrowthTimeline(ctx context.Context, arg GetVersionGrowthTimelineParams) ([]GetVersionGrowthTimelineRow, error)
	GetTopPackagesByVersionCount(ctx context.Context, arg GetTopPackagesByVersionCountParams) ([]GetTopPackagesByVersionCountRow, error)
}

// EnrichmentRepository defines data access methods for enrichment results.
type EnrichmentRepository interface {
	UpsertEnrichment(ctx context.Context, arg UpsertEnrichmentParams) error
	GetEnrichment(ctx context.Context, arg GetEnrichmentParams) (Enrichment, error)
	ListEnrichmentsBySBOM(ctx context.Context, sbomID pgtype.UUID) ([]ListEnrichmentsBySBOMRow, error)
	ListSBOMEnrichmentsByArtifact(ctx context.Context, artifactID pgtype.UUID) ([]ListSBOMEnrichmentsByArtifactRow, error)
}

// ArtifactRepository defines data access methods for artifact operations.
type ArtifactRepository interface {
	UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (pgtype.UUID, error)
	GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error)
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error)
	ListSBOMsByArtifact(ctx context.Context, arg ListSBOMsByArtifactParams) ([]ListSBOMsByArtifactRow, error)
	ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ListArtifactVersionsRow, error)
	CountArtifactVersions(ctx context.Context, arg CountArtifactVersionsParams) (int64, error)
	DeleteArtifact(ctx context.Context, id pgtype.UUID) (int64, error)
}

// RegistryRepository defines data access methods for registry management.
type RegistryRepository interface {
	CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error)
	GetRegistry(ctx context.Context, id pgtype.UUID) (Registry, error)
	ListRegistries(ctx context.Context, arg ListRegistriesParams) ([]Registry, error)
	ListRegistriesPaged(ctx context.Context, arg ListRegistriesPagedParams) ([]ListRegistriesPagedRow, error)
	UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error)
	SetRegistryEnabled(ctx context.Context, arg SetRegistryEnabledParams) (Registry, error)
	DeleteRegistry(ctx context.Context, id pgtype.UUID) (int64, error)
	ListPollableRegistries(ctx context.Context) ([]Registry, error)
	UpdateRegistryLastPolled(ctx context.Context, id pgtype.UUID) (Registry, error)
}

// JobRepository defines data access methods for scan job lifecycle.
type JobRepository interface {
	InsertScanJob(ctx context.Context, arg InsertScanJobParams) (ScanJob, error)
	StartScanJob(ctx context.Context, natsMsgID pgtype.Text) error
	FinishScanJob(ctx context.Context, arg FinishScanJobParams) error
	FailScanJob(ctx context.Context, arg FailScanJobParams) error
	ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJob, error)
	CountScanJobs(ctx context.Context, state pgtype.Text) (int64, error)
	CountScanJobsSince(ctx context.Context, arg CountScanJobsSinceParams) (int64, error)
	GetScanJob(ctx context.Context, id pgtype.UUID) (ScanJob, error)
	TimeoutScanJobs(ctx context.Context, startedBefore pgtype.Timestamptz) error
}

// AuthRepository defines data access methods for authentication and authorization.
type AuthRepository interface {
	UpsertUser(ctx context.Context, arg UpsertUserParams) (OcidexUser, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (OcidexUser, error)
	ListUsers(ctx context.Context) ([]OcidexUser, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (OcidexUser, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteExpiredSessions(ctx context.Context) error
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysByUserRow, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error)
}
