// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sbom.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSBOM = `-- name: DeleteSBOM :execrows
DELETE FROM sbom WHERE id = $1
`

func (q *Queries) DeleteSBOM(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSBOM, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertComponent = `-- name: InsertComponent :one
INSERT INTO component (
    sbom_id, parent_id, bom_ref, type, name, group_name,
    version, version_major, version_minor, version_patch,
    purl, cpe, description, scope, publisher, copyright
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16
)
RETURNING id
`

type InsertComponentParams struct {
	SbomID       pgtype.UUID `json:"sbom_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	BomRef       pgtype.Text `json:"bom_ref"`
	Type         string      `json:"type"`
	Name         string      `json:"name"`
	GroupName    pgtype.Text `json:"group_name"`
	Version      pgtype.Text `json:"version"`
	VersionMajor pgtype.Int4 `json:"version_major"`
	VersionMinor pgtype.Int4 `json:"version_minor"`
	VersionPatch pgtype.Int4 `json:"version_patch"`
	Purl         pgtype.Text `json:"purl"`
	Cpe          pgtype.Text `json:"cpe"`
	Description  pgtype.Text `json:"description"`
	Scope        pgtype.Text `json:"scope"`
	Publisher    pgtype.Text `json:"publisher"`
	Copyright    pgtype.Text `json:"copyright"`
}

func (q *Queries) InsertComponent(ctx context.Context, arg InsertComponentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertComponent,
		arg.SbomID,
		arg.ParentID,
		arg.BomRef,
		arg.Type,
		arg.Name,
		arg.GroupName,
		arg.Version,
		arg.VersionMajor,
		arg.VersionMinor,
		arg.VersionPatch,
		arg.Purl,
		arg.Cpe,
		arg.Description,
		arg.Scope,
		arg.Publisher,
		arg.Copyright,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertComponentHash = `-- name: InsertComponentHash :exec
INSERT INTO component_hash (component_id, algorithm, value)
VALUES ($1, $2, $3)
`

type InsertComponentHashParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	Algorithm   string      `json:"algorithm"`
	Value       string      `json:"value"`
}

func (q *Queries) InsertComponentHash(ctx context.Context, arg InsertComponentHashParams) error {
	_, err := q.db.Exec(ctx, insertComponentHash, arg.ComponentID, arg.Algorithm, arg.Value)
	return err
}

const insertComponentLicense = `-- name: InsertComponentLicense :exec
INSERT INTO component_license (component_id, license_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertComponentLicenseParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	LicenseID   pgtype.UUID `json:"license_id"`
}

func (q *Queries) InsertComponentLicense(ctx context.Context, arg InsertComponentLicenseParams) error {
	_, err := q.db.Exec(ctx, insertComponentLicense, arg.ComponentID, arg.LicenseID)
	return err
}

const insertDependency = `-- name: InsertDependency :exec
INSERT INTO dependency (sbom_id, ref, depends_on)
VALUES ($1, $2, $3)
`

type InsertDependencyParams struct {
	SbomID    pgtype.UUID `json:"sbom_id"`
	Ref       string      `json:"ref"`
	DependsOn string      `json:"depends_on"`
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) error {
	_, err := q.db.Exec(ctx, insertDependency, arg.SbomID, arg.Ref, arg.DependsOn)
	return err
}

const insertExternalReference = `-- name: InsertExternalReference :exec
INSERT INTO external_reference (component_id, type, url, comment)
VALUES ($1, $2, $3, $4)
`

type InsertExternalReferenceParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	Type        string      `json:"type"`
	Url         string      `json:"url"`
	Comment     pgtype.Text `json:"comment"`
}

func (q *Queries) InsertExternalReference(ctx context.Context, arg InsertExternalReferenceParams) error {
	_, err := q.db.Exec(ctx, insertExternalReference,
		arg.ComponentID,
		arg.Type,
		arg.Url,
		arg.Comment,
	)
	return err
}

const insertSBOM = `-- name: InsertSBOM :one
INSERT INTO sbom (serial_number, spec_version, version, raw_bom, artifact_id, subject_version, digest, registry_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, serial_number, spec_version, version, created_at
`

type InsertSBOMParams struct {
	SerialNumber   pgtype.Text `json:"serial_number"`
	SpecVersion    string      `json:"spec_version"`
	Version        int32       `json:"version"`
	RawBom         []byte      `json:"raw_bom"`
	ArtifactID     pgtype.UUID `json:"artifact_id"`
	SubjectVersion pgtype.Text `json:"subject_version"`
	Digest         pgtype.Text `json:"digest"`
	RegistryID     pgtype.UUID `json:"registry_id"`
}

type InsertSBOMRow struct {
	ID           pgtype.UUID        `json:"id"`
	SerialNumber pgtype.Text        `json:"serial_number"`
	SpecVersion  string             `json:"spec_version"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSBOM(ctx context.Context, arg InsertSBOMParams) (InsertSBOMRow, error) {
	row := q.db.QueryRow(ctx, insertSBOM,
		arg.SerialNumber,
		arg.SpecVersion,
		arg.Version,
		arg.RawBom,
		arg.ArtifactID,
		arg.SubjectVersion,
		arg.Digest,
		arg.RegistryID,
	)
	var i InsertSBOMRow
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.SpecVersion,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listDigestsByRegistry = `-- name: ListDigestsByRegistry :many
SELECT DISTINCT digest FROM sbom
WHERE registry_id = $1 AND digest IS NOT NULL
`

func (q *Queries) ListDigestsByRegistry(ctx context.Context, registryID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listDigestsByRegistry, registryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var digest pgtype.Text
		if err := rows.Scan(&digest); err != nil {
			return nil, err
		}
		items = append(items, digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSBOMSubjectVersion = `-- name: UpdateSBOMSubjectVersion :exec
UPDATE sbom SET subject_version = $2 WHERE id = $1
`

type UpdateSBOMSubjectVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	SubjectVersion pgtype.Text `json:"subject_version"`
}

func (q *Queries) UpdateSBOMSubjectVersion(ctx context.Context, arg UpdateSBOMSubjectVersionParams) error {
	_, err := q.db.Exec(ctx, updateSBOMSubjectVersion, arg.ID, arg.SubjectVersion)
	return err
}

const upsertLicenseByName = `-- name: UpsertLicenseByName :one
INSERT INTO license (name, url)
VALUES ($1, $2)
ON CONFLICT (name) WHERE spdx_id IS NULL
DO UPDATE SET url = COALESCE(EXCLUDED.url, license.url)
RETURNING id
`

type UpsertLicenseByNameParams struct {
	Name string      `json:"name"`
	Url  pgtype.Text `json:"url"`
}

func (q *Queries) UpsertLicenseByName(ctx context.Context, arg UpsertLicenseByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertLicenseByName, arg.Name, arg.Url)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertLicenseBySPDX = `-- name: UpsertLicenseBySPDX :one
INSERT INTO license (spdx_id, name, url)
VALUES ($1, $2, $3)
ON CONFLICT (spdx_id) WHERE spdx_id IS NOT NULL
DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertLicenseBySPDXParams struct {
	SpdxID pgtype.Text `json:"spdx_id"`
	Name   string      `json:"name"`
	Url    pgtype.Text `json:"url"`
}

func (q *Queries) UpsertLicenseBySPDX(ctx context.Context, arg UpsertLicenseBySPDXParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertLicenseBySPDX, arg.SpdxID, arg.Name, arg.Url)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
