// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScanJobs = `-- name: CountScanJobs :one
SELECT COUNT(*) FROM scan_jobs
WHERE ($1::text IS NULL OR state = $1::text)
`

func (q *Queries) CountScanJobs(ctx context.Context, state pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobs, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScanJobsSince = `-- name: CountScanJobsSince :one
SELECT COUNT(*) FROM scan_jobs
WHERE state = $1::text AND finished_at >= $2::timestamptz
`

type CountScanJobsSinceParams struct {
	State string             `json:"state"`
	Since pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountScanJobsSince(ctx context.Context, arg CountScanJobsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobsSince, arg.State, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs
SET state = 'failed', finished_at = now(), last_error = $1
WHERE nats_msg_id = $2
`

type FailScanJobParams struct {
	LastError pgtype.Text `json:"last_error"`
	NatsMsgID pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.db.Exec(ctx, failScanJob, arg.LastError, arg.NatsMsgID)
	return err
}

const finishScanJob = `-- name: FinishScanJob :exec
UPDATE scan_jobs
SET state = 'succeeded', finished_at = now(), sbom_id = $1::uuid
WHERE nats_msg_id = $2
`

type FinishScanJobParams struct {
	SbomID    pgtype.UUID `json:"sbom_id"`
	NatsMsgID pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) FinishScanJob(ctx context.Context, arg FinishScanJobParams) error {
	_, err := q.db.Exec(ctx, finishScanJob, arg.SbomID, arg.NatsMsgID)
	return err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, registry_id, repository, digest, tag, state, attempts, last_error, nats_msg_id, sbom_id, created_at, started_at, finished_at FROM scan_jobs WHERE id = $1
`

func (q *Queries) GetScanJob(ctx context.Context, id pgtype.UUID) (ScanJob, error) {
	row := q.db.QueryRow(ctx, getScanJob, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.RegistryID,
		&i.Repository,
		&i.Digest,
		&i.Tag,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.NatsMsgID,
		&i.SbomID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertScanJob = `-- name: InsertScanJob :one
INSERT INTO scan_jobs (registry_id, repository, digest, tag, nats_msg_id)
VALUES ($1::uuid, $2, $3, $4, $5)
RETURNING id, registry_id, repository, digest, tag, state, attempts, last_error, nats_msg_id, sbom_id, created_at, started_at, finished_at
`

type InsertScanJobParams struct {
	RegistryID pgtype.UUID `json:"registry_id"`
	Repository string      `json:"repository"`
	Digest     string      `json:"digest"`
	Tag        pgtype.Text `json:"tag"`
	NatsMsgID  pgtype.Text `json:"nats_msg_id"`
}

func (q *Queries) InsertScanJob(ctx context.Context, arg InsertScanJobParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, insertScanJob,
		arg.RegistryID,
		arg.Repository,
		arg.Digest,
		arg.Tag,
		arg.NatsMsgID,
	)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.RegistryID,
		&i.Repository,
		&i.Digest,
		&i.Tag,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.NatsMsgID,
		&i.SbomID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listScanJobs = `-- name: ListScanJobs :many
SELECT id, registry_id, repository, digest, tag, state, attempts, last_error, nats_msg_id, sbom_id, created_at, started_at, finished_at FROM scan_jobs
WHERE ($1::text IS NULL OR state = $1::text)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListScanJobsParams struct {
	State  pgtype.Text `json:"state"`
	Offset int32       `json:"offset_"`
	Limit  int32       `json:"limit_"`
}

func (q *Queries) ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJob, error) {
	rows, err := q.db.Query(ctx, listScanJobs, arg.State, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.RegistryID,
			&i.Repository,
			&i.Digest,
			&i.Tag,
			&i.State,
			&i.Attempts,
			&i.LastError,
			&i.NatsMsgID,
			&i.SbomID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startScanJob = `-- name: StartScanJob :exec
UPDATE scan_jobs
SET state = 'running', started_at = now(), attempts = attempts + 1
WHERE nats_msg_id = $1
`

func (q *Queries) StartScanJob(ctx context.Context, natsMsgID pgtype.Text) error {
	_, err := q.db.Exec(ctx, startScanJob, natsMsgID)
	return err
}
