// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSBOMComponents = `-- name: CountSBOMComponents :one
SELECT COUNT(*) FROM component WHERE sbom_id = $1
`

func (q *Queries) CountSBOMComponents(ctx context.Context, sbomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSBOMComponents, sbomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getComponent = `-- name: GetComponent :one
SELECT id, sbom_id, parent_id, bom_ref, type, name, group_name,
       version, purl, cpe, description, scope, publisher, copyright
FROM component
WHERE id = $1
`

type GetComponentRow struct {
	ID          pgtype.UUID `json:"id"`
	SbomID      pgtype.UUID `json:"sbom_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	BomRef      pgtype.Text `json:"bom_ref"`
	Type        string      `json:"type"`
	Name        string      `json:"name"`
	GroupName   pgtype.Text `json:"group_name"`
	Version     pgtype.Text `json:"version"`
	Purl        pgtype.Text `json:"purl"`
	Cpe         pgtype.Text `json:"cpe"`
	Description pgtype.Text `json:"description"`
	Scope       pgtype.Text `json:"scope"`
	Publisher   pgtype.Text `json:"publisher"`
	Copyright   pgtype.Text `json:"copyright"`
}

func (q *Queries) GetComponent(ctx context.Context, id pgtype.UUID) (GetComponentRow, error) {
	row := q.db.QueryRow(ctx, getComponent, id)
	var i GetComponentRow
	err := row.Scan(
		&i.ID,
		&i.SbomID,
		&i.ParentID,
		&i.BomRef,
		&i.Type,
		&i.Name,
		&i.GroupName,
		&i.Version,
		&i.Purl,
		&i.Cpe,
		&i.Description,
		&i.Scope,
		&i.Publisher,
		&i.Copyright,
	)
	return i, err
}

const getComponentVersions = `-- name: GetComponentVersions :many
SELECT c.id, c.sbom_id, c.type, c.name, c.group_name, c.version, c.purl,
       s.artifact_id, s.subject_version, s.digest AS sbom_digest,
       a.name AS artifact_name,
       s.created_at AS sbom_created_at,
       e.data->>'architecture' AS architecture
FROM component c
JOIN sbom s ON s.id = c.sbom_id
LEFT JOIN artifact a ON a.id = s.artifact_id
LEFT JOIN enrichment e ON e.sbom_id = s.id AND e.enricher_name = 'oci-metadata' AND e.status = 'success'
WHERE c.name = $1
  AND ($2::text IS NULL OR c.group_name = $2)
  AND ($3::text IS NULL OR c.version = $3)
  AND ($4::text IS NULL OR c.type = $4)
ORDER BY c.version_major DESC NULLS LAST,
         c.version_minor DESC NULLS LAST,
         c.version_patch DESC NULLS LAST,
         s.created_at DESC
`

type GetComponentVersionsParams struct {
	Name      string      `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
	Version   pgtype.Text `json:"version"`
	Type      pgtype.Text `json:"type"`
}

type GetComponentVersionsRow struct {
	ID             pgtype.UUID        `json:"id"`
	SbomID         pgtype.UUID        `json:"sbom_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	GroupName      pgtype.Text        `json:"group_name"`
	Version        pgtype.Text        `json:"version"`
	Purl           pgtype.Text        `json:"purl"`
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	SubjectVersion pgtype.Text        `json:"subject_version"`
	SbomDigest     pgtype.Text        `json:"sbom_digest"`
	ArtifactName   pgtype.Text        `json:"artifact_name"`
	SbomCreatedAt  pgtype.Timestamptz `json:"sbom_created_at"`
	Architecture   interface{}        `json:"architecture"`
}

func (q *Queries) GetComponentVersions(ctx context.Context, arg GetComponentVersionsParams) ([]GetComponentVersionsRow, error) {
	rows, err := q.db.Query(ctx, getComponentVersions,
		arg.Name,
		arg.GroupName,
		arg.Version,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetComponentVersionsRow{}
	for rows.Next() {
		var i GetComponentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SbomID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Version,
			&i.Purl,
			&i.ArtifactID,
			&i.SubjectVersion,
			&i.SbomDigest,
			&i.ArtifactName,
			&i.SbomCreatedAt,
			&i.Architecture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSBOM = `-- name: GetSBOM :one
SELECT id, serial_number, spec_version, version, artifact_id, subject_version, digest, created_at
FROM sbom
WHERE id = $1
`

type GetSBOMRow struct {
	ID             pgtype.UUID        `json:"id"`
	SerialNumber   pgtype.Text        `json:"serial_number"`
	SpecVersion    string             `json:"spec_version"`
	Version        int32              `json:"version"`
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	SubjectVersion pgtype.Text        `json:"subject_version"`
	Digest         pgtype.Text        `json:"digest"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSBOM(ctx context.Context, id pgtype.UUID) (GetSBOMRow, error) {
	row := q.db.QueryRow(ctx, getSBOM, id)
	var i GetSBOMRow
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.SpecVersion,
		&i.Version,
		&i.ArtifactID,
		&i.SubjectVersion,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const getSBOMByDigest = `-- name: GetSBOMByDigest :one
SELECT id FROM sbom WHERE digest = $1
`

func (q *Queries) GetSBOMByDigest(ctx context.Context, digest pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSBOMByDigest, digest)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getSBOMRaw = `-- name: GetSBOMRaw :one
SELECT raw_bom
FROM sbom
WHERE id = $1
`

func (q *Queries) GetSBOMRaw(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSBOMRaw, id)
	var raw_bom []byte
	err := row.Scan(&raw_bom)
	return raw_bom, err
}

const licenseSummaryByArtifact = `-- name: LicenseSummaryByArtifact :many
SELECT l.id, l.spdx_id, l.name, l.url, COUNT(DISTINCT cl.component_id) AS component_count
FROM sbom s
JOIN component c ON c.sbom_id = s.id
JOIN component_license cl ON cl.component_id = c.id
JOIN license l ON l.id = cl.license_id
WHERE s.artifact_id = $1
  AND s.id = (
    SELECT id FROM sbom WHERE artifact_id = $1 ORDER BY created_at DESC LIMIT 1
  )
GROUP BY l.id, l.spdx_id, l.name, l.url
ORDER BY component_count DESC, l.name
`

type LicenseSummaryByArtifactRow struct {
	ID             pgtype.UUID `json:"id"`
	SpdxID         pgtype.Text `json:"spdx_id"`
	Name           string      `json:"name"`
	Url            pgtype.Text `json:"url"`
	ComponentCount int64       `json:"component_count"`
}

func (q *Queries) LicenseSummaryByArtifact(ctx context.Context, artifactID pgtype.UUID) ([]LicenseSummaryByArtifactRow, error) {
	rows, err := q.db.Query(ctx, licenseSummaryByArtifact, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LicenseSummaryByArtifactRow{}
	for rows.Next() {
		var i LicenseSummaryByArtifactRow
		if err := rows.Scan(
			&i.ID,
			&i.SpdxID,
			&i.Name,
			&i.Url,
			&i.ComponentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentExtRefs = `-- name: ListComponentExtRefs :many
SELECT type, url, comment
FROM external_reference
WHERE component_id = $1
`

type ListComponentExtRefsRow struct {
	Type    string      `json:"type"`
	Url     string      `json:"url"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) ListComponentExtRefs(ctx context.Context, componentID pgtype.UUID) ([]ListComponentExtRefsRow, error) {
	rows, err := q.db.Query(ctx, listComponentExtRefs, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComponentExtRefsRow{}
	for rows.Next() {
		var i ListComponentExtRefsRow
		if err := rows.Scan(&i.Type, &i.Url, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentHashes = `-- name: ListComponentHashes :many
SELECT algorithm, value
FROM component_hash
WHERE component_id = $1
`

type ListComponentHashesRow struct {
	Algorithm string `json:"algorithm"`
	Value     string `json:"value"`
}

func (q *Queries) ListComponentHashes(ctx context.Context, componentID pgtype.UUID) ([]ListComponentHashesRow, error) {
	rows, err := q.db.Query(ctx, listComponentHashes, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComponentHashesRow{}
	for rows.Next() {
		var i ListComponentHashesRow
		if err := rows.Scan(&i.Algorithm, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentLicenses = `-- name: ListComponentLicenses :many
SELECT l.id, l.spdx_id, l.name, l.url
FROM license l
JOIN component_license cl ON cl.license_id = l.id
WHERE cl.component_id = $1
`

func (q *Queries) ListComponentLicenses(ctx context.Context, componentID pgtype.UUID) ([]License, error) {
	rows, err := q.db.Query(ctx, listComponentLicenses, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []License{}
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.SpdxID,
			&i.Name,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentPurlTypes = `-- name: ListComponentPurlTypes :many
SELECT DISTINCT split_part(replace(purl, 'pkg:', ''), '/', 1)::text AS purl_type
FROM component
WHERE purl IS NOT NULL
ORDER BY 1
`

func (q *Queries) ListComponentPurlTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listComponentPurlTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var purl_type string
		if err := rows.Scan(&purl_type); err != nil {
			return nil, err
		}
		items = append(items, purl_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByLicense = `-- name: ListComponentsByLicense :many
WITH ranked AS (
    SELECT c.id, c.sbom_id, c.type, c.name, c.group_name, c.version, c.purl,
           c.version_major, c.version_minor, c.version_patch,
           ROW_NUMBER() OVER (
               PARTITION BY c.name, COALESCE(c.group_name, ''), COALESCE(c.version, ''), c.type
               ORDER BY c.id
           ) AS rn
    FROM component c
    JOIN component_license cl ON cl.component_id = c.id
    WHERE cl.license_id = $3
)
SELECT id, sbom_id, type, name, group_name, version, purl,
       COUNT(*) OVER() AS total_count
FROM ranked
WHERE rn = 1
ORDER BY name,
         version_major DESC NULLS LAST,
         version_minor DESC NULLS LAST,
         version_patch DESC NULLS LAST
LIMIT $2 OFFSET $1
`

type ListComponentsByLicenseParams struct {
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
	LicenseID pgtype.UUID `json:"license_id"`
}

type ListComponentsByLicenseRow struct {
	ID         pgtype.UUID `json:"id"`
	SbomID     pgtype.UUID `json:"sbom_id"`
	Type       string      `json:"type"`
	Name       string      `json:"name"`
	GroupName  pgtype.Text `json:"group_name"`
	Version    pgtype.Text `json:"version"`
	Purl       pgtype.Text `json:"purl"`
	TotalCount int64       `json:"total_count"`
}

func (q *Queries) ListComponentsByLicense(ctx context.Context, arg ListComponentsByLicenseParams) ([]ListComponentsByLicenseRow, error) {
	rows, err := q.db.Query(ctx, listComponentsByLicense, arg.RowOffset, arg.RowLimit, arg.LicenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComponentsByLicenseRow{}
	for rows.Next() {
		var i ListComponentsByLicenseRow
		if err := rows.Scan(
			&i.ID,
			&i.SbomID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Version,
			&i.Purl,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesBySBOM = `-- name: ListDependenciesBySBOM :many
SELECT ref, depends_on
FROM dependency
WHERE sbom_id = $1
ORDER BY ref, depends_on
`

type ListDependenciesBySBOMRow struct {
	Ref       string `json:"ref"`
	DependsOn string `json:"depends_on"`
}

func (q *Queries) ListDependenciesBySBOM(ctx context.Context, sbomID pgtype.UUID) ([]ListDependenciesBySBOMRow, error) {
	rows, err := q.db.Query(ctx, listDependenciesBySBOM, sbomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependenciesBySBOMRow{}
	for rows.Next() {
		var i ListDependenciesBySBOMRow
		if err := rows.Scan(&i.Ref, &i.DependsOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicenses = `-- name: ListLicenses :many
SELECT l.id, l.spdx_id, l.name, l.url,
       COUNT(DISTINCT (c.name, COALESCE(c.group_name, ''), COALESCE(c.version, ''), c.type)) AS component_count,
       COUNT(*) OVER() AS total_count
FROM license l
LEFT JOIN component_license cl ON cl.license_id = l.id
LEFT JOIN component c ON c.id = cl.component_id
WHERE ($1::text IS NULL OR l.spdx_id = $1)
  AND ($2::text IS NULL OR l.name ILIKE $2)
  AND ($3::text IS NULL OR
    CASE
      WHEN l.spdx_id IS NULL THEN 'uncategorized'
      WHEN l.spdx_id IN (
        'GPL-2.0','GPL-2.0-only','GPL-2.0-or-later',
        'GPL-3.0','GPL-3.0-only','GPL-3.0-or-later',
        'AGPL-3.0','AGPL-3.0-only','AGPL-3.0-or-later',
        'SSPL-1.0','EUPL-1.2'
      ) THEN 'copyleft'
      WHEN l.spdx_id IN (
        'LGPL-2.0','LGPL-2.0-only','LGPL-2.0-or-later',
        'LGPL-2.1','LGPL-2.1-only','LGPL-2.1-or-later',
        'LGPL-3.0','LGPL-3.0-only','LGPL-3.0-or-later',
        'MPL-2.0','EPL-1.0','EPL-2.0','CDDL-1.0','CDDL-1.1'
      ) THEN 'weak-copyleft'
      ELSE 'permissive'
    END = $3::text)
GROUP BY l.id, l.spdx_id, l.name, l.url
ORDER BY component_count DESC, l.name
LIMIT $5 OFFSET $4
`

type ListLicensesParams struct {
	SpdxID    pgtype.Text `json:"spdx_id"`
	Name      pgtype.Text `json:"name"`
	Category  pgtype.Text `json:"category"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type ListLicensesRow struct {
	ID             pgtype.UUID `json:"id"`
	SpdxID         pgtype.Text `json:"spdx_id"`
	Name           string      `json:"name"`
	Url            pgtype.Text `json:"url"`
	ComponentCount int64       `json:"component_count"`
	TotalCount     int64       `json:"total_count"`
}

func (q *Queries) ListLicenses(ctx context.Context, arg ListLicensesParams) ([]ListLicensesRow, error) {
	rows, err := q.db.Query(ctx, listLicenses,
		arg.SpdxID,
		arg.Name,
		arg.Category,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLicensesRow{}
	for rows.Next() {
		var i ListLicensesRow
		if err := rows.Scan(
			&i.ID,
			&i.SpdxID,
			&i.Name,
			&i.Url,
			&i.ComponentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMComponents = `-- name: ListSBOMComponents :many
SELECT id, bom_ref, type, name, group_name, version, purl
FROM component
WHERE sbom_id = $1
ORDER BY name, group_name
`

type ListSBOMComponentsRow struct {
	ID        pgtype.UUID `json:"id"`
	BomRef    pgtype.Text `json:"bom_ref"`
	Type      string      `json:"type"`
	Name      string      `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
	Version   pgtype.Text `json:"version"`
	Purl      pgtype.Text `json:"purl"`
}

func (q *Queries) ListSBOMComponents(ctx context.Context, sbomID pgtype.UUID) ([]ListSBOMComponentsRow, error) {
	rows, err := q.db.Query(ctx, listSBOMComponents, sbomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMComponentsRow{}
	for rows.Next() {
		var i ListSBOMComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BomRef,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Version,
			&i.Purl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMs = `-- name: ListSBOMs :many
SELECT id, serial_number, spec_version, version, artifact_id, subject_version, digest, created_at,
       COUNT(*) OVER() AS total_count
FROM sbom
WHERE ($1::text IS NULL OR serial_number = $1)
  AND ($2::text IS NULL OR digest = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSBOMsParams struct {
	SerialNumber pgtype.Text `json:"serial_number"`
	Digest       pgtype.Text `json:"digest"`
	RowOffset    int32       `json:"row_offset"`
	RowLimit     int32       `json:"row_limit"`
}

type ListSBOMsRow struct {
	ID             pgtype.UUID        `json:"id"`
	SerialNumber   pgtype.Text        `json:"serial_number"`
	SpecVersion    string             `json:"spec_version"`
	Version        int32              `json:"version"`
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	SubjectVersion pgtype.Text        `json:"subject_version"`
	Digest         pgtype.Text        `json:"digest"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TotalCount     int64              `json:"total_count"`
}

func (q *Queries) ListSBOMs(ctx context.Context, arg ListSBOMsParams) ([]ListSBOMsRow, error) {
	rows, err := q.db.Query(ctx, listSBOMs,
		arg.SerialNumber,
		arg.Digest,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMsRow{}
	for rows.Next() {
		var i ListSBOMsRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.SpecVersion,
			&i.Version,
			&i.ArtifactID,
			&i.SubjectVersion,
			&i.Digest,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSBOMsByDigest = `-- name: ListSBOMsByDigest :many
SELECT id, serial_number, spec_version, version, artifact_id, subject_version, digest, created_at,
       COUNT(*) OVER() AS total_count
FROM sbom
WHERE digest = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListSBOMsByDigestParams struct {
	Digest    pgtype.Text `json:"digest"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type ListSBOMsByDigestRow struct {
	ID             pgtype.UUID        `json:"id"`
	SerialNumber   pgtype.Text        `json:"serial_number"`
	SpecVersion    string             `json:"spec_version"`
	Version        int32              `json:"version"`
	ArtifactID     pgtype.UUID        `json:"artifact_id"`
	SubjectVersion pgtype.Text        `json:"subject_version"`
	Digest         pgtype.Text        `json:"digest"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TotalCount     int64              `json:"total_count"`
}

func (q *Queries) ListSBOMsByDigest(ctx context.Context, arg ListSBOMsByDigestParams) ([]ListSBOMsByDigestRow, error) {
	rows, err := q.db.Query(ctx, listSBOMsByDigest, arg.Digest, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMsByDigestRow{}
	for rows.Next() {
		var i ListSBOMsByDigestRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.SpecVersion,
			&i.Version,
			&i.ArtifactID,
			&i.SubjectVersion,
			&i.Digest,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchComponents = `-- name: SearchComponents :many
SELECT c.id, c.sbom_id, c.type, c.name, c.group_name, c.version, c.purl,
       COUNT(*) OVER() AS total_count
FROM component c
WHERE c.name = $1
  AND ($2::text IS NULL OR c.group_name = $2)
  AND ($3::text IS NULL OR c.version = $3)
ORDER BY c.version_major DESC NULLS LAST,
         c.version_minor DESC NULLS LAST,
         c.version_patch DESC NULLS LAST
LIMIT $5 OFFSET $4
`

type SearchComponentsParams struct {
	Name      string      `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
	Version   pgtype.Text `json:"version"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type SearchComponentsRow struct {
	ID         pgtype.UUID `json:"id"`
	SbomID     pgtype.UUID `json:"sbom_id"`
	Type       string      `json:"type"`
	Name       string      `json:"name"`
	GroupName  pgtype.Text `json:"group_name"`
	Version    pgtype.Text `json:"version"`
	Purl       pgtype.Text `json:"purl"`
	TotalCount int64       `json:"total_count"`
}

func (q *Queries) SearchComponents(ctx context.Context, arg SearchComponentsParams) ([]SearchComponentsRow, error) {
	rows, err := q.db.Query(ctx, searchComponents,
		arg.Name,
		arg.GroupName,
		arg.Version,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchComponentsRow{}
	for rows.Next() {
		var i SearchComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SbomID,
			&i.Type,
			&i.Name,
			&i.GroupName,
			&i.Version,
			&i.Purl,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDistinctComponents = `-- name: SearchDistinctComponents :many
SELECT c.name, c.group_name, c.type,
       COALESCE(string_agg(DISTINCT split_part(replace(c.purl, 'pkg:', ''), '/', 1), ',' ORDER BY split_part(replace(c.purl, 'pkg:', ''), '/', 1)) FILTER (WHERE c.purl IS NOT NULL), '') AS purl_types,
       COUNT(DISTINCT c.version) FILTER (WHERE c.version IS NOT NULL) AS version_count,
       COUNT(DISTINCT c.sbom_id) AS sbom_count,
       COUNT(*) OVER() AS total_count
FROM component c
WHERE ($1::text IS NULL OR c.name ILIKE $1)
  AND ($2::text IS NULL OR c.group_name = $2)
  AND ($3::text IS NULL OR c.type = $3)
  AND ($4::text IS NULL OR split_part(replace(c.purl, 'pkg:', ''), '/', 1) = $4)
GROUP BY c.name, c.group_name, c.type
ORDER BY
  CASE $5::text
    WHEN 'version_count' THEN COUNT(DISTINCT c.version) FILTER (WHERE c.version IS NOT NULL)
    WHEN 'sbom_count' THEN COUNT(DISTINCT c.sbom_id)
  END * CASE $6::text WHEN 'asc' THEN 1 ELSE -1 END ASC NULLS LAST,
  c.name, c.group_name
LIMIT $8 OFFSET $7
`

type SearchDistinctComponentsParams struct {
	Name      pgtype.Text `json:"name"`
	GroupName pgtype.Text `json:"group_name"`
	Type      pgtype.Text `json:"type"`
	PurlType  pgtype.Text `json:"purl_type"`
	SortBy    string      `json:"sort_by"`
	SortDir   string      `json:"sort_dir"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type SearchDistinctComponentsRow struct {
	Name         string      `json:"name"`
	GroupName    pgtype.Text `json:"group_name"`
	Type         string      `json:"type"`
	PurlTypes    interface{} `json:"purl_types"`
	VersionCount int64       `json:"version_count"`
	SbomCount    int64       `json:"sbom_count"`
	TotalCount   int64       `json:"total_count"`
}

func (q *Queries) SearchDistinctComponents(ctx context.Context, arg SearchDistinctComponentsParams) ([]SearchDistinctComponentsRow, error) {
	rows, err := q.db.Query(ctx, searchDistinctComponents,
		arg.Name,
		arg.GroupName,
		arg.Type,
		arg.PurlType,
		arg.SortBy,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDistinctComponentsRow{}
	for rows.Next() {
		var i SearchDistinctComponentsRow
		if err := rows.Scan(
			&i.Name,
			&i.GroupName,
			&i.Type,
			&i.PurlTypes,
			&i.VersionCount,
			&i.SbomCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
