// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLicenseCategoryCounts = `-- name: GetLicenseCategoryCounts :many
SELECT
    license_category(l.spdx_id) AS category,
    COUNT(DISTINCT cl.component_id)::bigint AS component_count
FROM license l
JOIN component_license cl ON cl.license_id = l.id
JOIN component c ON c.id = cl.component_id
WHERE EXISTS (SELECT 1 FROM sbom s WHERE s.id = c.sbom_id
    AND sbom_visible(s.registry_id, $1::uuid, $2::boolean))
GROUP BY 1
ORDER BY component_count DESC
`

type GetLicenseCategoryCountsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetLicenseCategoryCountsRow struct {
	Category       string `json:"category"`
	ComponentCount int64  `json:"component_count"`
}

func (q *Queries) GetLicenseCategoryCounts(ctx context.Context, arg GetLicenseCategoryCountsParams) ([]GetLicenseCategoryCountsRow, error) {
	rows, err := q.db.Query(ctx, getLicenseCategoryCounts, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLicenseCategoryCountsRow{}
	for rows.Next() {
		var i GetLicenseCategoryCountsRow
		if err := rows.Scan(&i.Category, &i.ComponentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackageGrowthTimeline = `-- name: GetPackageGrowthTimeline :many
WITH pkg_first_seen AS (
    SELECT DATE(MIN(s.created_at)) AS first_seen
    FROM component c
    JOIN sbom s ON s.id = c.sbom_id
    WHERE sbom_visible(s.registry_id, $1::uuid, $2::boolean)
    GROUP BY c.name, COALESCE(c.group_name, ''), c.type
),
daily_new AS (
    SELECT first_seen, COUNT(*)::bigint AS new_count
    FROM pkg_first_seen
    WHERE first_seen <= CURRENT_DATE
    GROUP BY first_seen
)
SELECT
    first_seen::text AS day,
    SUM(new_count) OVER (ORDER BY first_seen)::bigint AS cumulative_count
FROM daily_new
ORDER BY first_seen
`

type GetPackageGrowthTimelineParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetPackageGrowthTimelineRow struct {
	Day             string `json:"day"`
	CumulativeCount int64  `json:"cumulative_count"`
}

// Cumulative distinct packages (name+group+type) by the day each first appeared.
func (q *Queries) GetPackageGrowthTimeline(ctx context.Context, arg GetPackageGrowthTimelineParams) ([]GetPackageGrowthTimelineRow, error) {
	rows, err := q.db.Query(ctx, getPackageGrowthTimeline, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPackageGrowthTimelineRow{}
	for rows.Next() {
		var i GetPackageGrowthTimelineRow
		if err := rows.Scan(&i.Day, &i.CumulativeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSBOMIngestionTimeline = `-- name: GetSBOMIngestionTimeline :many
SELECT
    DATE(s.created_at)::text AS day,
    COUNT(*)::bigint         AS count
FROM sbom s
WHERE s.created_at >= CURRENT_DATE - $1::int
  AND DATE(s.created_at) <= CURRENT_DATE
  AND sbom_visible(s.registry_id, $2::uuid, $3::boolean)
GROUP BY DATE(s.created_at)::text
ORDER BY day
`

type GetSBOMIngestionTimelineParams struct {
	NumDays int32       `json:"num_days"`
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetSBOMIngestionTimelineRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) GetSBOMIngestionTimeline(ctx context.Context, arg GetSBOMIngestionTimelineParams) ([]GetSBOMIngestionTimelineRow, error) {
	rows, err := q.db.Query(ctx, getSBOMIngestionTimeline, arg.NumDays, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSBOMIngestionTimelineRow{}
	for rows.Next() {
		var i GetSBOMIngestionTimelineRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryCounts = `-- name: GetSummaryCounts :one
SELECT
    (SELECT COUNT(*)::bigint FROM artifact a
       WHERE artifact_visible(a.id, $1::uuid, $2::boolean)
    ) AS artifact_count,
    (SELECT COUNT(*)::bigint FROM sbom s
       WHERE sbom_visible(s.registry_id, $1::uuid, $2::boolean)
    ) AS sbom_count,
    (SELECT COUNT(*)::bigint FROM (
        SELECT DISTINCT c.name, COALESCE(c.group_name,'') AS g, c.type
        FROM component c
        WHERE EXISTS (SELECT 1 FROM sbom s WHERE s.id = c.sbom_id
            AND sbom_visible(s.registry_id, $1::uuid, $2::boolean))
    ) t) AS package_count,
    (SELECT COUNT(*)::bigint FROM (
        SELECT DISTINCT c.name, COALESCE(c.group_name,'') AS g, COALESCE(c.version,'') AS v, c.type
        FROM component c
        WHERE EXISTS (SELECT 1 FROM sbom s WHERE s.id = c.sbom_id
            AND sbom_visible(s.registry_id, $1::uuid, $2::boolean))
    ) t) AS version_count,
    (SELECT COUNT(*)::bigint FROM license) AS license_count
`

type GetSummaryCountsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetSummaryCountsRow struct {
	ArtifactCount int64 `json:"artifact_count"`
	SbomCount     int64 `json:"sbom_count"`
	PackageCount  int64 `json:"package_count"`
	VersionCount  int64 `json:"version_count"`
	LicenseCount  int64 `json:"license_count"`
}

func (q *Queries) GetSummaryCounts(ctx context.Context, arg GetSummaryCountsParams) (GetSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, getSummaryCounts, arg.UserID, arg.IsAdmin)
	var i GetSummaryCountsRow
	err := row.Scan(
		&i.ArtifactCount,
		&i.SbomCount,
		&i.PackageCount,
		&i.VersionCount,
		&i.LicenseCount,
	)
	return i, err
}

const getTopPackagesByVersionCount = `-- name: GetTopPackagesByVersionCount :many
SELECT
    c.name,
    c.group_name,
    c.type,
    COUNT(DISTINCT COALESCE(c.version, ''))::bigint AS version_count,
    COUNT(DISTINCT c.sbom_id)::bigint               AS sbom_count
FROM component c
WHERE EXISTS (SELECT 1 FROM sbom s WHERE s.id = c.sbom_id
    AND sbom_visible(s.registry_id, $1::uuid, $2::boolean))
GROUP BY c.name, c.group_name, c.type
ORDER BY version_count DESC
LIMIT $3::int
`

type GetTopPackagesByVersionCountParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
	TopN    int32       `json:"top_n"`
}

type GetTopPackagesByVersionCountRow struct {
	Name         string      `json:"name"`
	GroupName    pgtype.Text `json:"group_name"`
	Type         string      `json:"type"`
	VersionCount int64       `json:"version_count"`
	SbomCount    int64       `json:"sbom_count"`
}

func (q *Queries) GetTopPackagesByVersionCount(ctx context.Context, arg GetTopPackagesByVersionCountParams) ([]GetTopPackagesByVersionCountRow, error) {
	rows, err := q.db.Query(ctx, getTopPackagesByVersionCount, arg.UserID, arg.IsAdmin, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopPackagesByVersionCountRow{}
	for rows.Next() {
		var i GetTopPackagesByVersionCountRow
		if err := rows.Scan(
			&i.Name,
			&i.GroupName,
			&i.Type,
			&i.VersionCount,
			&i.SbomCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVersionGrowthTimeline = `-- name: GetVersionGrowthTimeline :many
WITH ver_first_seen AS (
    SELECT DATE(MIN(s.created_at)) AS first_seen
    FROM component c
    JOIN sbom s ON s.id = c.sbom_id
    WHERE sbom_visible(s.registry_id, $1::uuid, $2::boolean)
    GROUP BY c.name, COALESCE(c.group_name, ''), COALESCE(c.version, ''), c.type
),
daily_new AS (
    SELECT first_seen, COUNT(*)::bigint AS new_count
    FROM ver_first_seen
    WHERE first_seen <= CURRENT_DATE
    GROUP BY first_seen
)
SELECT
    first_seen::text AS day,
    SUM(new_count) OVER (ORDER BY first_seen)::bigint AS cumulative_count
FROM daily_new
ORDER BY first_seen
`

type GetVersionGrowthTimelineParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

type GetVersionGrowthTimelineRow struct {
	Day             string `json:"day"`
	CumulativeCount int64  `json:"cumulative_count"`
}

// Cumulative distinct package versions (name+group+version+type) by the day each first appeared.
func (q *Queries) GetVersionGrowthTimeline(ctx context.Context, arg GetVersionGrowthTimelineParams) ([]GetVersionGrowthTimelineRow, error) {
	rows, err := q.db.Query(ctx, getVersionGrowthTimeline, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVersionGrowthTimelineRow{}
	for rows.Next() {
		var i GetVersionGrowthTimelineRow
		if err := rows.Scan(&i.Day, &i.CumulativeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
