// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLicenseCategoryCounts = `-- name: GetLicenseCategoryCounts :many
SELECT
    CASE
        WHEN l.spdx_id IS NOT NULL AND l.spdx_id ~* 'GPL|AGPL|EUPL|CDDL|OSL|CC-BY-SA' THEN 'copyleft'
        WHEN l.spdx_id IS NOT NULL AND l.spdx_id ~* 'LGPL|MPL|EPL|CPAL|APSL'          THEN 'weak-copyleft'
        WHEN l.spdx_id IS NOT NULL                                                      THEN 'permissive'
        ELSE 'uncategorized'
    END AS category,
    COUNT(DISTINCT cl.component_id)::bigint AS component_count
FROM license l
JOIN component_license cl ON cl.license_id = l.id
GROUP BY 1
ORDER BY component_count DESC
`

type GetLicenseCategoryCountsRow struct {
	Category       string `json:"category"`
	ComponentCount int64  `json:"component_count"`
}

func (q *Queries) GetLicenseCategoryCounts(ctx context.Context) ([]GetLicenseCategoryCountsRow, error) {
	rows, err := q.db.Query(ctx, getLicenseCategoryCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLicenseCategoryCountsRow{}
	for rows.Next() {
		var i GetLicenseCategoryCountsRow
		if err := rows.Scan(&i.Category, &i.ComponentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackageGrowthTimeline = `-- name: GetPackageGrowthTimeline :many
WITH pkg_first_seen AS (
    SELECT DATE(MIN(s.created_at)) AS first_seen
    FROM component c
    JOIN sbom s ON s.id = c.sbom_id
    GROUP BY c.name, COALESCE(c.group_name, ''), c.type
),
daily_new AS (
    SELECT first_seen, COUNT(*)::bigint AS new_count
    FROM pkg_first_seen
    WHERE first_seen <= CURRENT_DATE
    GROUP BY first_seen
)
SELECT
    first_seen::text AS day,
    SUM(new_count) OVER (ORDER BY first_seen)::bigint AS cumulative_count
FROM daily_new
ORDER BY first_seen
`

type GetPackageGrowthTimelineRow struct {
	Day             string `json:"day"`
	CumulativeCount int64  `json:"cumulative_count"`
}

// Cumulative distinct packages (name+group+type) by the day each first appeared.
func (q *Queries) GetPackageGrowthTimeline(ctx context.Context) ([]GetPackageGrowthTimelineRow, error) {
	rows, err := q.db.Query(ctx, getPackageGrowthTimeline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPackageGrowthTimelineRow{}
	for rows.Next() {
		var i GetPackageGrowthTimelineRow
		if err := rows.Scan(&i.Day, &i.CumulativeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSBOMIngestionTimeline = `-- name: GetSBOMIngestionTimeline :many
SELECT
    DATE(created_at)::text AS day,
    COUNT(*)::bigint       AS count
FROM sbom
WHERE created_at >= CURRENT_DATE - $1::int
  AND DATE(created_at) <= CURRENT_DATE
GROUP BY DATE(created_at)::text
ORDER BY day
`

type GetSBOMIngestionTimelineRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) GetSBOMIngestionTimeline(ctx context.Context, numDays int32) ([]GetSBOMIngestionTimelineRow, error) {
	rows, err := q.db.Query(ctx, getSBOMIngestionTimeline, numDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSBOMIngestionTimelineRow{}
	for rows.Next() {
		var i GetSBOMIngestionTimelineRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryCounts = `-- name: GetSummaryCounts :one
SELECT
    (SELECT COUNT(*)::bigint FROM artifact)  AS artifact_count,
    (SELECT COUNT(*)::bigint FROM sbom)      AS sbom_count,
    (SELECT COUNT(*)::bigint FROM (SELECT DISTINCT name, COALESCE(group_name,'') AS g, type FROM component) t) AS package_count,
    (SELECT COUNT(*)::bigint FROM (SELECT DISTINCT name, COALESCE(group_name,'') AS g, COALESCE(version,'') AS v, type FROM component) t) AS version_count,
    (SELECT COUNT(*)::bigint FROM license)   AS license_count
`

type GetSummaryCountsRow struct {
	ArtifactCount int64 `json:"artifact_count"`
	SbomCount     int64 `json:"sbom_count"`
	PackageCount  int64 `json:"package_count"`
	VersionCount  int64 `json:"version_count"`
	LicenseCount  int64 `json:"license_count"`
}

func (q *Queries) GetSummaryCounts(ctx context.Context) (GetSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, getSummaryCounts)
	var i GetSummaryCountsRow
	err := row.Scan(
		&i.ArtifactCount,
		&i.SbomCount,
		&i.PackageCount,
		&i.VersionCount,
		&i.LicenseCount,
	)
	return i, err
}

const getTopPackagesByVersionCount = `-- name: GetTopPackagesByVersionCount :many
SELECT
    name,
    group_name,
    type,
    COUNT(DISTINCT COALESCE(version, ''))::bigint AS version_count,
    COUNT(DISTINCT sbom_id)::bigint               AS sbom_count
FROM component
GROUP BY name, group_name, type
ORDER BY version_count DESC
LIMIT $1::int
`

type GetTopPackagesByVersionCountRow struct {
	Name         string      `json:"name"`
	GroupName    pgtype.Text `json:"group_name"`
	Type         string      `json:"type"`
	VersionCount int64       `json:"version_count"`
	SbomCount    int64       `json:"sbom_count"`
}

func (q *Queries) GetTopPackagesByVersionCount(ctx context.Context, topN int32) ([]GetTopPackagesByVersionCountRow, error) {
	rows, err := q.db.Query(ctx, getTopPackagesByVersionCount, topN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopPackagesByVersionCountRow{}
	for rows.Next() {
		var i GetTopPackagesByVersionCountRow
		if err := rows.Scan(
			&i.Name,
			&i.GroupName,
			&i.Type,
			&i.VersionCount,
			&i.SbomCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVersionGrowthTimeline = `-- name: GetVersionGrowthTimeline :many
WITH ver_first_seen AS (
    SELECT DATE(MIN(s.created_at)) AS first_seen
    FROM component c
    JOIN sbom s ON s.id = c.sbom_id
    GROUP BY c.name, COALESCE(c.group_name, ''), COALESCE(c.version, ''), c.type
),
daily_new AS (
    SELECT first_seen, COUNT(*)::bigint AS new_count
    FROM ver_first_seen
    WHERE first_seen <= CURRENT_DATE
    GROUP BY first_seen
)
SELECT
    first_seen::text AS day,
    SUM(new_count) OVER (ORDER BY first_seen)::bigint AS cumulative_count
FROM daily_new
ORDER BY first_seen
`

type GetVersionGrowthTimelineRow struct {
	Day             string `json:"day"`
	CumulativeCount int64  `json:"cumulative_count"`
}

// Cumulative distinct package versions (name+group+version+type) by the day each first appeared.
func (q *Queries) GetVersionGrowthTimeline(ctx context.Context) ([]GetVersionGrowthTimelineRow, error) {
	rows, err := q.db.Query(ctx, getVersionGrowthTimeline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVersionGrowthTimelineRow{}
	for rows.Next() {
		var i GetVersionGrowthTimelineRow
		if err := rows.Scan(&i.Day, &i.CumulativeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
