// Package main exports the OpenAPI spec generated by huma to stdout.
// It constructs the router with nil services (no handlers are invoked)
// and serialises the resulting OpenAPI 3.1 spec as JSON.
//
// Usage:
//
//	go run ./cmd/specgen > web/openapi.json
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/pfenerty/ocidex/internal/api"
)

func main() {
	h := api.NewHandler(nil, nil, nil, nil, nil, nil, nil)
	_ = api.NewRouter(h, "*", "", "")

	spec := h.API().OpenAPI()

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(spec); err != nil {
		fmt.Fprintf(os.Stderr, "error encoding spec: %v\n", err)
		os.Exit(1)
	}
}
