apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocidex-api
spec:
  template:
    spec:
      containers:
        - name: ocidex-api
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_STREAM_REPLICAS
              value: "1"
